spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: reservationGroup
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    template:
      default-topic: reservation

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      hotelReservationService:
        connectionTimeout: 5000
        readTimeout: 5000
        logerLevel: basic
      carReservationService:
        connectionTimeout: 5000
        readTimeout: 5000
        logerLevel: basic
      flightReservationService:
        connectionTimeout: 5000
        readTimeout: 5000
        logerLevel: basic

server:
  port: 8082
