spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: reservationGroup
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    template:
      default-topic: reservation

server:
  port: 8082
